// AUTO-GENERATED BY scripts/sync-apim-to-db.ts
// DO NOT EDIT MANUALLY

export interface ExtractedResource {
    id: string;
    name: string;
    type: string;
    environment: 'DEV' | 'QA' | 'STAGE' | 'PROD';
    details: any;
    isOrphaned: boolean;
}

export const MOCK_ORPHANED_DATA: ExtractedResource[] = [
    {
        "id": "prod-dev-1",
        "name": "Legacy Service 1 (DEV)",
        "type": "Product",
        "environment": "DEV",
        "details": {
            "displayName": "Legacy Service 1",
            "state": "published",
            "description": "Imported from DEV APIM. Needs ownership assignment.",
            "subscriptionRequired": true
        },
        "isOrphaned": true
    },
    {
        "id": "api-dev-1",
        "name": "legacy-api-1",
        "type": "API",
        "environment": "DEV",
        "details": {
            "displayName": "Legacy API 1",
            "path": "/legacy/dev/v1",
            "protocols": [
                "https"
            ],
            "associatedProduct": "prod-dev-1"
        },
        "isOrphaned": true
    },
    {
        "id": "nv-dev-1",
        "name": "db-secret-1",
        "type": "NamedValue",
        "environment": "DEV",
        "details": {
            "displayName": "DB_CONNECTION_STRING",
            "secret": true,
            "tags": [
                "migrated"
            ]
        },
        "isOrphaned": true
    },
    {
        "id": "backend-dev-1",
        "name": "backend-service-1",
        "type": "Backend",
        "environment": "DEV",
        "details": {
            "url": "https://api-legacy-1.dev.internal",
            "protocol": "http"
        },
        "isOrphaned": true
    },
    {
        "id": "prod-qa-1",
        "name": "Legacy Service 1 (QA)",
        "type": "Product",
        "environment": "QA",
        "details": {
            "displayName": "Legacy Service 1",
            "state": "published",
            "description": "Imported from QA APIM. Needs ownership assignment.",
            "subscriptionRequired": true
        },
        "isOrphaned": true
    },
    {
        "id": "api-qa-1",
        "name": "legacy-api-1",
        "type": "API",
        "environment": "QA",
        "details": {
            "displayName": "Legacy API 1",
            "path": "/legacy/qa/v1",
            "protocols": [
                "https"
            ],
            "associatedProduct": "prod-qa-1"
        },
        "isOrphaned": true
    },
    {
        "id": "prod-grp-orphan-1",
        "name": "Global Mobile Bundle (GRP)",
        "type": "Product",
        "environment": "PROD",
        "details": {
            "displayName": "Mobile App Bundle (GRP)",
            "state": "published",
            "description": "Orphaned GRP Product. Should only map Product, not APIs.",
            "subscriptionRequired": true,
            "type": "grp"
        },
        "isOrphaned": true
    }
];
