// AUTO-GENERATED BY scripts/sync-apim-to-db.ts
// DO NOT EDIT MANUALLY

export interface ExtractedResource {
    id: string;
    name: string;
    type: string;
    environment: 'DEV' | 'QA' | 'STAGE' | 'PROD';
    details: any;
    isOrphaned: boolean;
}

export const MOCK_ORPHANED_DATA: ExtractedResource[] = [
    {
        "id": "prod-dev-payments",
        "name": "payments-service",
        "type": "Product",
        "environment": "DEV",
        "details": {
            "displayName": "Digital Payments Suite",
            "state": "published",
            "description": "Core payment processing product. Terraform managed.",
            "subscriptionRequired": true,
            "managementMode": "TERRAFORM_MANAGED",
            "gitRepoUrl": "https://dev.azure.com/org/project/_git/apim-iac-payments",
            "lastDeployedCommitHash": "8f2a1bc3df6a123456789abcdef",
            "pipelineInfo": {
                "url": "https://dev.azure.com/org/project/_build?definitionId=101"
            }
        },
        "isOrphaned": true
    },
    {
        "id": "api-dev-payments-v1",
        "name": "payments-api-v1",
        "type": "API",
        "environment": "DEV",
        "details": {
            "displayName": "Payments REST API",
            "path": "/payments/v1",
            "protocols": ["https"],
            "associatedProduct": "prod-dev-payments",
            "gitRepoUrl": "https://dev.azure.com/org/project/_git/apim-iac-payments",
            "gitFilePath": "contracts/payments-v1.yaml"
        },
        "isOrphaned": true
    },
    {
        "id": "prod-qa-identity",
        "name": "identity-service",
        "type": "Product",
        "environment": "QA",
        "details": {
            "displayName": "Identity & Access Manager",
            "state": "published",
            "description": "Legacy identity portal. Manual management.",
            "subscriptionRequired": true,
            "managementMode": "PORTAL_MANAGED"
        },
        "isOrphaned": true
    },
    {
        "id": "prod-grp-mobile",
        "name": "grp-mobile-banking",
        "type": "Product",
        "environment": "PROD",
        "details": {
            "displayName": "Mobile Banking Bundle (GRP)",
            "state": "published",
            "description": "Global bundle for mobile banking. APIs owned by Producer teams.",
            "subscriptionRequired": true,
            "type": "grp",
            "managementMode": "TERRAFORM_MANAGED",
            "gitRepoUrl": "https://dev.azure.com/org/project/_git/grp-mobile-banking"
        },
        "isOrphaned": true
    }
];
