/**
 * @fileoverview Data Extraction Script for "Day 1" Onboarding
 * 
 * Purpose:
 * Simulate the extraction of existing APIM resources (Products, APIs, NamedValues, Backends)
 * into a local "DB" format (JSON) for the new Self-Service Portal.
 * 
 * Critical Rules:
 * 1. SKIP PROD: All resources from PROD environments are explicitly excluded.
 * 2. ORPHANS: All extracted resources are initially "orphaned" (ownerTeamId: null).
 * 3. DEEP EXTRACT: Captures Named Values, Backends, and Certs.
 * 
 * Usage:
 * npx ts-node scripts/sync-apim-to-db.ts
 */

import fs from 'fs';
import path from 'path';

// Types (Mirrors src/types/entities.ts but for "raw" extraction)
interface ExtractedResource {
    id: string;
    name: string;
    type: string; // Product, API, NamedValue, Backend
    environment: 'DEV' | 'QA' | 'STAGE' | 'PROD';
    details: any;
    isOrphaned: boolean;
}

const ENVIRONMENTS = ['DEV', 'QA', 'STAGE', 'PROD'];

// --- MOCK AZURE CLIENT ---
// Simulates fetching from actual Azure Resource Groups
const mockAzureFetch = async (env: string) => {
    console.log(`[Azure] Connecting to Subscription (Env: ${env})...`);

    if (env === 'PROD') {
        console.warn(`[Azure] SKIPPING PROD Environment (${env}) - Governance Rule Applied.`);
        return [];
    }

    // Generate Mock Data specific to the environment
    const resources: ExtractedResource[] = [];
    const count = env === 'DEV' ? 5 : 3;

    for (let i = 1; i <= count; i++) {
        // 1. PRODUCT
        const pid = `prod-${env.toLowerCase()}-${i}`;
        resources.push({
            id: pid,
            name: `Legacy Service ${i} (${env})`,
            type: 'Product',
            environment: env as any,
            details: {
                displayName: `Legacy Service ${i}`,
                state: 'published',
                description: `Imported from ${env} APIM. Needs ownership assignment.`,
                subscriptionRequired: true
            },
            isOrphaned: true // DAY 1 STATE
        });

        // 2. API (inside Product)
        resources.push({
            id: `api-${env.toLowerCase()}-${i}`,
            name: `legacy-api-${i}`,
            type: 'API',
            environment: env as any,
            details: {
                displayName: `Legacy API ${i}`,
                path: `/legacy/${env.toLowerCase()}/v${i}`,
                protocols: ['https'],
                associatedProduct: pid
            },
            isOrphaned: true
        });

        // 3. NAMED VALUES (Secrets)
        resources.push({
            id: `nv-${env.toLowerCase()}-${i}`,
            name: `db-secret-${i}`,
            type: 'NamedValue',
            environment: env as any,
            details: {
                displayName: `DB_CONNECTION_STRING`,
                secret: true,
                tags: ['migrated']
            },
            isOrphaned: true
        });

        // 4. BACKEND
        resources.push({
            id: `backend-${env.toLowerCase()}-${i}`,
            name: `backend-service-${i}`,
            type: 'Backend',
            environment: env as any,
            details: {
                url: `https://api-legacy-${i}.${env.toLowerCase()}.internal`,
                protocol: 'http'
            },
            isOrphaned: true
        });
    }

    return resources;
};

// --- MAIN SYNC LOGIC ---
const main = async () => {
    console.log('=== STARTING APIM EXTRACTION (DAY 1) ===');
    const allResources: ExtractedResource[] = [];

    for (const env of ENVIRONMENTS) {
        const envResources = await mockAzureFetch(env);
        allResources.push(...envResources);
    }

    console.log('=== EXTRACTION COMPLETE ===');
    console.log(`Total Resources Found: ${allResources.length}`);
    console.log(`- Products: ${allResources.filter(r => r.type === 'Product').length}`);
    console.log(`- APIs: ${allResources.filter(r => r.type === 'API').length}`);
    console.log(`- Config items: ${allResources.filter(r => r.type === 'NamedValue' || r.type === 'Backend').length}`);

    // Verify Exclusion
    const prodCount = allResources.filter(r => r.environment === 'PROD').length;
    if (prodCount > 0) {
        console.error('!!! FATAL ERROR: PROD RESOURCES DETECTED !!!');
        process.exit(1);
    } else {
        console.log('✅ PROD Environment successfully excluded.');
    }

    // Save to "DB" (Mock File for Admin UI to read)
    const outputPath = path.resolve(process.cwd(), 'src/features/inventory/api/mockOrphanedData.json');
    fs.writeFileSync(outputPath, JSON.stringify(allResources, null, 2));

    // Also generate a TypeScript export for easier importing in the app
    const tsOutputPath = path.resolve(process.cwd(), 'src/features/inventory/api/mockOrphanedData.ts');
    const tsContent = `// AUTO-GENERATED BY scripts/sync-apim-to-db.ts
// DO NOT EDIT MANUALLY
export const MOCK_ORPHANED_DATA = ${JSON.stringify(allResources, null, 4)};`;

    fs.writeFileSync(tsOutputPath, tsContent);

    console.log(`✅ Data saved to: ${tsOutputPath}`);
};

main().catch(console.error);
