import { PolicyFlow, PolicyStep } from '../types/policyTypes';

/**
 * Generates the full Azure APIM Policy XML from the visual Flow state.
 */
export const generatePolicyXml = (flow: PolicyFlow): string => {
    return `<!-- Generated by APIM Self-Service Portal -->
<policies>
    <inbound>
        ${flow.inbound.map(generateStepXml).join('\n        ')}
    </inbound>
    <backend>
        ${flow.backend.map(generateStepXml).join('\n        ')}
    </backend>
    <outbound>
        ${flow.outbound.map(generateStepXml).join('\n        ')}
    </outbound>
    <on-error>
        ${flow.onError.map(generateStepXml).join('\n        ')}
    </on-error>
</policies>`;
};

const generateStepXml = (step: PolicyStep): string => {
    // If it's a locked policy (inherited), we primarily rely on the <base /> tag
    // appearing in the flow, but typically specific locked steps are just visual placeholders.
    // However, if we preserve specific xmlSnippets for them, use those.
    if (step.xmlSnippet) {
        return step.xmlSnippet; // Use the pre-baked snippet if available (e.g. <base />)
    }

    switch (step.type) {
        case 'rate-limit':
            const { calls = 10, renewalPeriod = 60, counterKey } = step.properties;
            return `<rate-limit-by-key calls="${calls}" renewal-period="${renewalPeriod}" counter-key="${counterKey || '@(context.Subscription.Id)'}" />`;

        case 'validate-jwt':
            const { headerName, failedValidationErrorMessage, requireScheme } = step.properties;
            // Simplified generation for demo
            return `<validate-jwt header-name="${headerName || 'Authorization'}" failed-validation-error-message="${failedValidationErrorMessage || 'Unauthorized'}" require-scheme="${requireScheme || 'Bearer'}">
            <openid-config url="https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration" />
        </validate-jwt>`;

        case 'cors':
            return `<cors allow-credentials="true">
            <allowed-origins>
                <origin>*</origin>
            </allowed-origins>
            <allowed-methods>
                <method>GET</method>
                <method>POST</method>
            </allowed-methods>
        </cors>`;

        case 'ip-filter':
            return `<ip-filter action="forbid">
            <address-range from="0.0.0.0" to="255.255.255.255" />
        </ip-filter>`;

        case 'mock-response':
            return `<mock-response status-code="200" content-type="application/json" />`;

        case 'set-header':
            return `<set-header name="X-Generated-By" exists-action="override">
            <value>Self-Service-Portal</value>
        </set-header>`;

        case 'custom-xml':
            return step.customXmlContent || `<!-- Custom XML Block -->`;

        default:
            return `<!-- Unknown Step Type: ${step.type} -->`;
    }
};
